# -*- coding: utf-8 -*-
"""Untitled98.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10dsGMOTEEkgqi8zx2WEmRzRtwUoAzsEn
"""

# 10 tickets
# 1 golden, 9 regular

tickets <- c("gold", rep("blank", 9))
tickets

# pick random
# replace param is used to "return" tickets back to hat after taking it out
set.seed(2)

play_game_fnc <- function() {
tickets.random <- sample(tickets, size=20, replace=TRUE, prob=rep(0.1, 10))
# print out random picks
#tickets.random


tickets.table <- table(tickets.random)
golds <- tickets.table[2]

ifelse(is.na(golds), 0, golds[[1]])
}

library(purrr)
games <- map_int(1:1000, ~play_game_fnc())
games

cat("avg gold:", mean(games), "\n")

install.packages("ggplot2")
library(ggplot2)
g_df <- data.frame(golds=games)
ggplot(g_df, aes(x=golds)) +
  geom_density(alpha=0.5, fill="blue", color="blue")

# 1 or 2 -> -1$
# 3 or 4 or 5 -> 0$
# 6 -> +3$

outcome <- c(-1, 0, 3)
probs <- c(2/6, 3/6, 1/6)

rounds <- sample(outcome, size = 2, replace=TRUE, prob=probs)
mean(rounds)
sum(rounds)

throw_dice <- function(n_rounds){
  r <- sample(outcome, size = n_rounds, replace=TRUE, prob=probs)
  r
}

sims <- map(1:1, ~throw_dice(20))
sims


library(purrr)

outcome <- 1:6
probs <- rep(1/6, 6)

throw_dice <- function(n_rounds){
  r <- sample(outcome, size = n_rounds, replace = TRUE, prob = probs)
  r
}

sims <- map(1:10000, ~throw_dice(20))


sims %>%
  map_dbl(sum) %>%
  {. < 0} %>%
  mean()

library(purrr)
library(ggplot2)
library(dplyr)

outcome <- 1:6
probs <- rep(1/6, 6)

check_four_sixes <- function() {
  r <- sample(outcome, size = 4, replace = TRUE, prob = probs)
  return(all(r == 6))
}

set.seed(42)
n_simulations <- 10000000
mat_sims <- map_lgl(1:n_simulations, ~check_four_sixes())

vjerojatnost <- mean(mat_sims)

cat("Aproksimirana vjerojatnost:", vjerojatnost, "\n")
cat("Teoretska vjerojatnost:   ", (1/6)^4, "\n")

library(purrr)
library(ggplot2)
library(dplyr)

outcome <- 1:6
probs <- rep(1/6, 6)

check_sum_seven <- function() {
  r <- sample(outcome, size = 2, replace = TRUE, prob = probs)
  return(sum(r) >= 7)
}

set.seed(42)
n_simulations <- 10000000


mat_sims <- map_lgl(1:n_simulations, ~check_sum_seven(), .progress = "Simulacija")

vjerojatnost <- mean(mat_sims)

cat("\nAproksimirana vjerojatnost (Suma >= 7):", vjerojatnost, "\n")
cat("Teoretska vjerojatnost (21/36):       ", 21/36, "\n")